<!DOCTYPE html>
<html lang="en-US">
<head>

<title>Home Page</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/css/bootstrap.min.css">

</head>
<body>

<div class="container col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">Home Page</div>
    <div class="panel-body">
      <a href="/login" class="col-md-6">Login</a>
      <a href="/register" class="col-md-6">Register</a>
    </div>
  </div>
</div>

</body>
</html>

