<!DOCTYPE html>
<html lang="en-US">
<head>

<title>User Login</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/css/bootstrap.min.css">

<script type='text/javascript' src="/js/login.js"></script>
<link rel="stylesheet" href="/css/style.css">

<script type='text/javascript'>
  $(document).ready(function() {
    Login.init();
  });
</script>

</head>
<body>

<div class="container col-md-4 col-md-offset-4">
  <h2>User Login</h2>
  <div class="panel panel-default">
    <div class="panel-heading">Login</div>
    <div class="panel-body">
      <div class="error"><?= $error ?></div>
      <form role="form" method="POST" action="/login">
        <div class="form-group" id="username">
          <label for="username">Username:</label>
          <input type="username" class="form-control" name="username" value="<?= $username ?>" required>
          <span class="error"></span>
        </div>
        <div class="form-group" id="password">
          <label for="password">Password:</label>
          <input type="password" class="form-control" name="password" required>
          <span class="error"></span>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>

</body>
</html>
