<!DOCTYPE html>
<html lang="en-US">
<head>

<title>User Signup</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/css/bootstrap.min.css">

<script type='text/javascript' src="/js/register.js"></script>
<link rel="stylesheet" href="/css/style.css">

<script type='text/javascript'>
  $(document).ready(function() {
    Register.init();
  });
</script>
</head>
<body>

<div class="container col-md-6 col-md-offset-3">
  <h2>User Register</h2>
  <div class="panel panel-default">
    <div class="panel-heading">Register</div>
    <div class="panel-body">
      <div class="error"><?= $error ?></div>
      <form method="POST" action="/register">
        <div class="body bg-gray">
            <div class="form-group row">
               <div class="col-sm-4">
                 <label for="username">Username:<span class="required"> * </span></label>
               </div>
               <div class="col-sm-8">
                 <input type="text" placeholder="Username" class="form-control" name="username" value="<?= $username ?>" required>
               </div>
            </div>
            <div class="form-group row">
               <div class="col-sm-4">
                 <label for="email">Email:<span class="required"> * </span></label>
               </div>
               <div class="col-sm-8">
                 <input type="text" placeholder="Email Address" class="form-control" name="email" value="<?= $email ?>" required>
               </div>
            </div>
            <div class="form-group row">
               <div class="col-sm-4">
                 <label for="telephone">Telephone:</label>
               </div>
               <div class="col-sm-8">
                 <input type="text" placeholder="Telephone" class="form-control" name="telephone" value="<?= $telphone ?>">
               </div>
            </div>
            <div class="form-group row">
               <div class="col-sm-4">
                 <label for="password">Password:<span class="required"> * </span></label>
               </div>
               <div class="col-sm-8">
               <input type="password" placeholder="Password" class="form-control" name="password" required>
               </div>
            </div>
            <div class="form-group row">
               <div class="col-sm-4">
                 <label for="password2">Confirm Password:<span class="required"> * </span></label>
               </div>
               <div class="col-sm-8">
                 <input type="password" placeholder="Retype password" class="form-control" name="password2" required>
               </div>
            </div>
        </div>
        <div class="footer">
          <button class="btn btn-primary col-md-offset-5" type="submit">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>

</body>
</html>
